1. Sales Data Analysis

Use Case: Analyze sales data for trends, customer segmentation, or performance.

Operations:

• Count total sales per product category.

• Calculate the total revenue generated by each sales representative.

• Find the product with the highest sales.

• Group data by sales regions and calculate average sales.

In [ ]:
import numpy as np

In [ ]:
# Sample dataset
# Columns: SalesRep, Region, ProductCategory, UnitsSold, UnitPrice
data = np.array([
    ['John', 'North', 'Electronics', 10, 100],
    ['Alice', 'South', 'Furniture', 5, 200],
    ['Bob', 'North', 'Electronics', 8, 100],
    ['Alice', 'East', 'Clothing', 15, 50],
    ['John', 'West', 'Furniture', 7, 200],
    ['Bob', 'South', 'Clothing', 12, 50],
    ['John', 'East', 'Electronics', 6, 100],
    ['Alice', 'North', 'Furniture', 3, 200],
], dtype=object)

In [ ]:
# Convert UnitsSold and UnitPrice to numbers
sales_rep = data[:, 0]
region = data[:, 1]
product_category = data[:, 2]
units_sold = data[:, 3].astype(int)
unit_price = data[:, 4].astype(float)

In [ ]:
# Total sales for each row
total_sales = units_sold * unit_price
total_sales

array([1000., 1000.,  800.,  750., 1400.,  600.,  600.,  600.])

In [ ]:
# 1. Total sales per product category
print("Total Sales per Product Category:")
for category in np.unique(product_category):
    sales = units_sold[product_category == category].sum()
    print(f"{category}: {sales}")

Total Sales per Product Category:
Clothing: 27
Electronics: 24
Furniture: 15


In [ ]:
# 2. Total revenue per sales representative
print("\nTotal Revenue per Sales Representative:")
for rep in np.unique(sales_rep):
    revenue = total_sales[sales_rep == rep].sum()
    print(f"{rep}: ${revenue}")


Total Revenue per Sales Representative:
Alice: $2350.0
Bob: $1400.0
John: $3000.0


In [ ]:
# 3. Product with the highest sales (UnitsSold)
max_idx = np.argmax(units_sold)
print("\nHighest Selling Product:", data[max_idx,2])


Highest Selling Product: Clothing


In [ ]:
# 4. Average sales per region
print("\nAverage Sales per Region:")
for reg in np.unique(region):
    avg_sales = units_sold[region == reg].mean()
    print(f"{reg}: {avg_sales:.2f}")


Average Sales per Region:
East: 10.50
North: 7.00
South: 8.50
West: 7.00


2. Employee Data Analysis:

Use Case: Manage and analyze employee-related data like salaries, departments, and performance.

Operations:

• Count the number of employees per department.

• Find the employee with the highest salary.

• Calculate average salary per department.

• Sort employees based on their performance score or salary.


In [ ]:
# Sample employee dataset
# Columns: EmployeeName, Department, Salary, PerformanceScore
data = np.array([
    ['John', 'HR', 50000, 85],
    ['Alice', 'IT', 70000, 90],
    ['Bob', 'Finance', 60000, 88],
    ['Eve', 'IT', 72000, 92],
    ['Charlie', 'Finance', 58000, 80],
    ['Daisy', 'HR', 52000, 86],
    ['Frank', 'IT', 75000, 95],
    ['Grace', 'Finance', 61000, 83]
], dtype=object)

In [ ]:
# Extract relevant columns
employees = data[:, 0]
departments = data[:, 1]
salaries = data[:, 2].astype(float)
performance = data[:, 3].astype(int)

In [ ]:
# 1. Count number of employees per department
print("Number of Employees per Department:")
for dept in np.unique(departments):
    count = len(employees[departments == dept])
    print(f"{dept}: {count}")


Number of Employees per Department:
Finance: 3
HR: 2
IT: 3


In [ ]:
# 2. Find the employee with the highest salary
highest_salary_index = np.argmax(salaries)
print(f"\nEmployee with Highest Salary: {employees[highest_salary_index]} (${salaries[highest_salary_index]})")


Employee with Highest Salary: Frank ($75000.0)


In [ ]:
# 3. Calculate average salary per department
print("\nAverage Salary per Department:")
for dept in np.unique(departments):
    avg_salary = salaries[departments == dept].mean()
    print(f"{dept}: ${avg_salary:.2f}")


Average Salary per Department:
Finance: $59666.67
HR: $51000.00
IT: $72333.33


In [ ]:
# 4. Sort employees by performance score
sorted_by_performance = data[np.argsort(performance)[::-1]]
print("\nEmployees Sorted by Performance (High to Low):")
print(sorted_by_performance)


Employees Sorted by Performance (High to Low):
[['Frank' 'IT' 75000 95]
 ['Eve' 'IT' 72000 92]
 ['Alice' 'IT' 70000 90]
 ['Bob' 'Finance' 60000 88]
 ['Daisy' 'HR' 52000 86]
 ['John' 'HR' 50000 85]
 ['Grace' 'Finance' 61000 83]
 ['Charlie' 'Finance' 58000 80]]


In [ ]:
# 5. Sort employees by salary
sorted_by_salary = data[np.argsort(salaries)[::-1]]
print("\nEmployees Sorted by Salary (High to Low):")
for row in sorted_by_salary:
    print(row)


Employees Sorted by Salary (High to Low):
['Frank' 'IT' 75000 95]
['Eve' 'IT' 72000 92]
['Alice' 'IT' 70000 90]
['Grace' 'Finance' 61000 83]
['Bob' 'Finance' 60000 88]
['Charlie' 'Finance' 58000 80]
['Daisy' 'HR' 52000 86]
['John' 'HR' 50000 85]


3. Student Grades Analysis

Use Case: Analyze academic performance of students across subjects.

Operations:

• Count the number of students who passed each subject.

• Calculate the average marks per subject.

• Find the student with the highest total marks.

• Determine the top 3 students based on average marks.


In [ ]:
# Sample data: [StudentName, Math, Science, English]
data = np.array([
    ['John', 78, 85, 90],
    ['Alice', 92, 88, 95],
    ['Bob', 60, 65, 70],
    ['Eve', 80, 75, 85],
    ['Charlie', 55, 50, 65],
    ['Daisy', 70, 72, 68],
    ['Frank', 88, 90, 84],
    ['Grace', 95, 92, 96]
], dtype=object)

In [ ]:
# Separate names and marks
names = data[:, 0]
marks = data[:, 1:].astype(float)

In [ ]:
# 1. Count number of students who passed each subject (pass mark = 40)
print("Pass Count per Subject:")
for i, subject in enumerate(["Math", "Science", "English"]):
    print(f"{subject}: {np.sum(marks[:, i] >= 40)}")

Pass Count per Subject:
Math: 8
Science: 8
English: 8


In [ ]:
# 2. Average marks per subject
print("\nAverage Marks per Subject:")
for i, subject in enumerate(["Math", "Science", "English"]):
    print(f"{subject}: {marks[:, i].mean():.2f}")


Average Marks per Subject:
Math: 77.25
Science: 77.12
English: 81.62


In [ ]:
# 3. Student with highest total marks
total_marks = marks.sum(axis=1)
top_student = names[np.argmax(total_marks)]
print(f"\nTop Scorer: {top_student} with {total_marks.max()} marks")


Top Scorer: Grace with 283.0 marks


In [ ]:
# 4. Top 3 students based on average marks
avg_marks = marks.mean(axis=1)
top_3 = np.argsort(avg_marks)[::-1][:3]  # Sort descending and take top 3
print("\nTop 3 Students:")
for i in top_3:
    print(f"{names[i]} - {avg_marks[i]:.2f}")


Top 3 Students:
Grace - 94.33
Alice - 91.67
Frank - 87.33


4. Weather Data Analysis

Use Case: Work with temperature/rainfall data to identify patterns.

Operations:

• Find the maximum and minimum temperature recorded each month.

• Calculate average rainfall per season.

• Count how many days had temperature above a threshold (e.g., >35°C).

• Identify the month with the highest average temperature.


In [ ]:
import numpy as np

# Sample weather data: [Month, Day, Temperature(°C), Rainfall(mm)]
data = np.array([
    ['Jan', 1, 30, 5],
    ['Jan', 2, 32, 0],
    ['Jan', 3, 29, 2],
    ['Feb', 1, 33, 0],
    ['Feb', 2, 31, 1],
    ['Mar', 1, 36, 0],
    ['Mar', 2, 38, 0],
    ['Apr', 1, 40, 2],
    ['Apr', 2, 39, 5],
    ['May', 1, 34, 8],
    ['May', 2, 35, 6],
    ['Jun', 1, 30, 15],
    ['Jun', 2, 32, 20]
], dtype=object)


In [ ]:
# Separate columns
months = data[:, 0]
temperature = data[:, 2].astype(float)
rainfall = data[:, 3].astype(float)

In [ ]:
# 1. Max and Min temperature for each month
print("Max and Min Temperature Each Month:")
for month in np.unique(months):
    temp_in_month = temperature[months == month]
    print(f"{month} -> Max: {temp_in_month.max()}°C, Min: {temp_in_month.min()}°C")

Max and Min Temperature Each Month:
Apr -> Max: 40.0°C, Min: 39.0°C
Feb -> Max: 33.0°C, Min: 31.0°C
Jan -> Max: 32.0°C, Min: 29.0°C
Jun -> Max: 32.0°C, Min: 30.0°C
Mar -> Max: 38.0°C, Min: 36.0°C
May -> Max: 35.0°C, Min: 34.0°C


In [ ]:
# 2. Average rainfall per season
# Define seasons
seasons = {
    'Winter': ['Dec', 'Jan', 'Feb'],
    'Spring': ['Mar', 'Apr', 'May'],
    'Summer': ['Jun', 'Jul', 'Aug'],
    'Autumn': ['Sep', 'Oct', 'Nov']
}

print("\nAverage Rainfall per Season:")
for season, season_months in seasons.items():
    season_rain = rainfall[np.isin(months, season_months)]
    if len(season_rain) > 0:
        print(f"{season}: {season_rain.mean():.2f} mm")


Average Rainfall per Season:
Winter: 1.60 mm
Spring: 3.50 mm
Summer: 17.50 mm


In [ ]:
# 3. Count days with temperature > 35°C
hot_days = np.sum(temperature > 35)
print(f"\nDays with Temperature > 35°C: {hot_days}")


Days with Temperature > 35°C: 4


In [ ]:
#4. Identify the month with the highest average temperature.


# Step 1: Get the list of unique months
unique_months = np.unique(months)

# Step 2: Compute average temperature for each unique month
avg_temp_per_month = []
for m in unique_months:
    month_avg = temperature[months == m].mean()
    avg_temp_per_month.append(month_avg)

# Step 3: Find the index of the highest average temperature
max_index = np.argmax(avg_temp_per_month)

# Step 4: Use the index to get the corresponding hottest month
hottest_month = unique_months[max_index]

# Step 5: Display the result
print("\nMonth with Highest Average Temperature:", hottest_month)



Month with Highest Average Temperature: Apr


5. Stock Market Data Analysis

Use Case: Analyze stock prices for investment insights.

Operations:

• Calculate daily returns for each stock.

• Find the stock with the highest average return.

• Count how many days each stock had a positive return.

• Determine the maximum drawdown (largest fall from peak price).

In [ ]:
import numpy as np

# Sample stock data
# Columns: Day, StockA, StockB, StockC
data = np.array([
    [1, 100, 200, 300],
    [2, 102, 198, 310],
    [3, 101, 202, 305],
    [4, 104, 205, 315],
    [5, 103, 204, 310],
    [6, 107, 207, 320],
    [7, 105, 210, 318]
], dtype=float)

# Separate stock prices (skip day column)
prices = data[:, 1:]

stock_names = ["StockA", "StockB", "StockC"]

# 1. Calculate daily returns for each stock
# Daily return = (Today's Price - Yesterday's Price) / Yesterday's Price
daily_returns = (prices[1:] - prices[:-1]) / prices[:-1]

print("Daily Returns (%):")
for i, name in enumerate(stock_names):
    print(f"{name}: {np.round(daily_returns[:, i] * 100, 2)}")

# 2. Find stock with highest average return
avg_returns = daily_returns.mean(axis=0)
best_stock = stock_names[np.argmax(avg_returns)]
print(f"\nStock with Highest Average Return: {best_stock} ({avg_returns.max() * 100:.2f}%)")

# 3. Count how many days each stock had positive return
print("\nDays with Positive Return:")
for i, name in enumerate(stock_names):
    positive_days = np.sum(daily_returns[:, i] > 0)
    print(f"{name}: {positive_days} days")

# 4. Determine maximum drawdown for each stock
print("\nMaximum Drawdown (Largest Drop from Peak Price):")
for i, name in enumerate(stock_names):
    stock_prices = prices[:, i]
    peak = stock_prices[0]
    max_drawdown = 0
    for price in stock_prices:
        peak = max(peak, price)  # Track the highest price seen so far
        drawdown = (peak - price) / peak
        max_drawdown = max(max_drawdown, drawdown)
    print(f"{name}: {max_drawdown * 100:.2f}%")


Daily Returns (%):
StockA: [ 2.   -0.98  2.97 -0.96  3.88 -1.87]
StockB: [-1.    2.02  1.49 -0.49  1.47  1.45]
StockC: [ 3.33 -1.61  3.28 -1.59  3.23 -0.62]

Stock with Highest Average Return: StockC (1.00%)

Days with Positive Return:
StockA: 3 days
StockB: 4 days
StockC: 3 days

Maximum Drawdown (Largest Drop from Peak Price):
StockA: 1.87%
StockB: 1.00%
StockC: 1.61%


6. Hospital Patient Data Analysis

Use Case: Manage and analyze patient records for healthcare insights.

Operations:

• Count the number of patients per disease category.

• Find the patient with the longest hospital stay.

• Calculate average age of patients per department.

• Identify the most common diagnosis.


In [ ]:
# Sample hospital dataset
# Columns: PatientName, Age, Department, Disease, DaysAdmitted
data = np.array([
    ['John', 45, 'Cardiology', 'Heart Disease', 10],
    ['Alice', 30, 'Neurology', 'Migraine', 5],
    ['Bob', 60, 'Orthopedics', 'Fracture', 15],
    ['Eve', 50, 'Cardiology', 'Heart Disease', 7],
    ['Charlie', 35, 'Neurology', 'Epilepsy', 12],
    ['Daisy', 40, 'Orthopedics', 'Fracture', 9],
    ['Frank', 55, 'Cardiology', 'Hypertension', 6],
    ['Grace', 28, 'Neurology', 'Migraine', 4]
], dtype=object)

# Separate relevant columns
ages = data[:, 1].astype(int)
departments = data[:, 2]
diseases = data[:, 3]
days_admitted = data[:, 4].astype(int)

# 1. Count number of patients per disease category
print("Number of Patients per Disease Category:")
for disease in np.unique(diseases):
    count = np.sum(diseases == disease)
    print(f"{disease}: {count}")

# 2. Find the patient with the longest hospital stay
longest_stay_index = np.argmax(days_admitted)
print(f"\nPatient with Longest Stay: {data[longest_stay_index, 0]} ({days_admitted[longest_stay_index]} days)")

# 3. Calculate average age per department
print("\nAverage Age per Department:")
for dept in np.unique(departments):
    avg_age = ages[departments == dept].mean()
    print(f"{dept}: {avg_age:.2f} years")

# 4. Identify the most common diagnosis
unique_diseases, counts = np.unique(diseases, return_counts=True)
most_common_disease = unique_diseases[np.argmax(counts)]
print(f"\nMost Common Diagnosis: {most_common_disease}")


Number of Patients per Disease Category:
Epilepsy: 1
Fracture: 2
Heart Disease: 2
Hypertension: 1
Migraine: 2

Patient with Longest Stay: Bob (15 days)

Average Age per Department:
Cardiology: 50.00 years
Neurology: 31.00 years
Orthopedics: 50.00 years

Most Common Diagnosis: Fracture


7. E-commerce Website Traffic Analysis

Use Case: Study website visitor data for patterns.

Operations:

• Count the number of visitors per day/week.

• Find the day with the highest number of visitors.

• Calculate average time spent by users on the website.

• Determine bounce rate (users who visited only 1 page).

In [ ]:
# Sample website traffic dataset
# Columns: Day, Visitors, AvgTimeSpent(mins), PagesVisited
data = np.array([
    ['Mon', 120, 5.5, 2],
    ['Tue', 150, 6.0, 1],
    ['Wed', 170, 6.5, 3],
    ['Thu', 200, 7.0, 1],
    ['Fri', 180, 5.8, 2],
    ['Sat', 220, 8.0, 4],
    ['Sun', 250, 9.0, 1]
], dtype=object)

# Separate columns
days = data[:, 0]
visitors = data[:, 1].astype(int)
avg_time_spent = data[:, 2].astype(float)
pages_visited = data[:, 3].astype(int)

# 1. Count number of visitors per day
print("Visitors per Day:")
for i, day in enumerate(days):
    print(f"{day}: {visitors[i]}")

# Total visitors in the week
total_visitors_week = visitors.sum()
print(f"\nTotal Visitors in the Week: {total_visitors_week}")

# 2. Day with the highest number of visitors
max_visitors_day = days[np.argmax(visitors)]
print(f"\nDay with Highest Visitors: {max_visitors_day} ({visitors.max()} visitors)")

# 3. Calculate average time spent by users
overall_avg_time = avg_time_spent.mean()
print(f"\nOverall Average Time Spent: {overall_avg_time:.2f} mins")

# 4. Calculate bounce rate (users who visited only 1 page)
# Bounce Rate = (Users who visited 1 page / Total Visitors) * 100
# Assume "PagesVisited = 1" means bounce
bounce_visitors = visitors[pages_visited == 1].sum()
bounce_rate = (bounce_visitors / total_visitors_week) * 100
print(f"\nBounce Rate: {bounce_rate:.2f}%")


Visitors per Day:
Mon: 120
Tue: 150
Wed: 170
Thu: 200
Fri: 180
Sat: 220
Sun: 250

Total Visitors in the Week: 1290

Day with Highest Visitors: Sun (250 visitors)

Overall Average Time Spent: 6.83 mins

Bounce Rate: 46.51%


8. Transportation Data Analysis

Use Case: Analyze public transport usage across routes and timings.

Operations:

• Count the number of passengers per route.

• Calculate average occupancy per bus/train.

• Find the route with maximum passengers.

• Identify peak hours of usage.

In [ ]:
# Sample transportation dataset
# Columns: Route, Hour(24hr format), Passengers, TotalCapacity
data = np.array([
    ['R1', 8, 45, 50],
    ['R1', 9, 40, 50],
    ['R1', 17, 48, 50],
    ['R2', 8, 30, 40],
    ['R2', 18, 35, 40],
    ['R2', 19, 38, 40],
    ['R3', 7, 25, 30],
    ['R3', 8, 28, 30],
    ['R3', 17, 30, 30],
    ['R4', 9, 20, 30],
    ['R4', 18, 25, 30]
], dtype=object)

# Separate columns
routes = data[:, 0]
hours = data[:, 1].astype(int)
passengers = data[:, 2].astype(int)
capacity = data[:, 3].astype(int)

# 1. Count the number of passengers per route
print("Total Passengers per Route:")
for route in np.unique(routes):
    total_passengers = passengers[routes == route].sum()
    print(f"{route}: {total_passengers}")

# 2. Calculate average occupancy per bus/train
# Occupancy = (Passengers / Capacit


Total Passengers per Route:
R1: 133
R2: 103
R3: 83
R4: 45


9. Retail Store Inventory Analysis

Use Case: Manage and analyze product stock levels.

Operations:
• Count the total number of products in stock.

• Find the product with the lowest inventory.

• Calculate average stock per product category.

• Identify products that need restocking (below threshold).

In [ ]:
import numpy as np

# Sample retail store inventory dataset
# Columns: Product, Category, Stock
data = np.array([
    ['Shampoo', 'Personal Care', 50],
    ['Soap', 'Personal Care', 30],
    ['Toothpaste', 'Personal Care', 15],
    ['Rice', 'Groceries', 100],
    ['Sugar', 'Groceries', 40],
    ['Flour', 'Groceries', 25],
    ['T-shirt', 'Clothing', 20],
    ['Jeans', 'Clothing', 10],
    ['Shoes', 'Footwear', 5],
    ['Slippers', 'Footwear', 12]
], dtype=object)

# Separate columns
products = data[:, 0]
categories = data[:, 1]
stock = data[:, 2].astype(int)

# 1. Count the total number of products in stock
total_stock = stock.sum()
print(f"Total Stock Across All Products: {total_stock}")

# 2. Find the product with the lowest inventory
min_stock_index = np.argmin(stock)
print(f"Product with Lowest Inventory: {products[min_stock_index]} ({stock[min_stock_index]} units)")

# 3. Calculate average stock per product category
print("\nAverage Stock per Category:")
for cat in np.unique(categories):
    avg_stock = stock[categories == cat].mean()
    print(f"{cat}: {avg_stock:.2f}")

# 4. Identify products that need restocking (threshold = 15 units)
threshold = 15
restock_needed = products[stock < threshold]
print("\nProducts that need restocking (below 15 units):")
if restock_needed.size > 0:
    for item in restock_needed:
        print(item)
else:
    print("No products need restocking!")


Total Stock Across All Products: 307
Product with Lowest Inventory: Shoes (5 units)

Average Stock per Category:
Clothing: 15.00
Footwear: 8.50
Groceries: 55.00
Personal Care: 31.67

Products that need restocking (below 15 units):
Jeans
Shoes
Slippers


10. Sports Team Performance Analysis

Use Case: Analyze performance of players and teams across matches.

Operations:

• Count the number of wins per team.

• Find the player with the highest average score.

• Calculate total goals/runs/points scored by each team.

• Determine the most consistent performer based on statistics.

In [ ]:
import numpy as np

# Sample sports performance dataset
# Columns: Match, Team, Player, Score, Result(W/L)
data = np.array([
    [1, 'Team A', 'Player 1', 20, 'W'],
    [1, 'Team B', 'Player 4', 15, 'L'],
    [2, 'Team A', 'Player 2', 25, 'L'],
    [2, 'Team B', 'Player 5', 30, 'W'],
    [3, 'Team A', 'Player 3', 18, 'W'],
    [3, 'Team B', 'Player 6', 10, 'L'],
    [4, 'Team A', 'Player 1', 22, 'W'],
    [4, 'Team B', 'Player 5', 28, 'L'],
    [5, 'Team A', 'Player 2', 15, 'L'],
    [5, 'Team B', 'Player 4', 35, 'W']
], dtype=object)

# Separate columns
teams = data[:, 1]
players = data[:, 2]
scores = data[:, 3].astype(int)
results = data[:, 4]

# 1. Count the number of wins per team
print("Wins per Team:")
for team in np.unique(teams):
    wins = np.sum((teams == team) & (results == 'W'))
    print(f"{team}: {wins}")

# 2. Find the player with the highest average score
unique_players = np.unique(players)
avg_scores = [scores[players == player].mean() for player in unique_players]
max_avg_index = np.argmax(avg_scores)
print(f"\nPlayer with Highest Average Score: {unique_players[max_avg_index]} ({avg_scores[max_avg_index]:.2f} points)")

# 3. Calculate total score by each team
print("\nTotal Score by Team:")
for team in np.unique(teams):
    total_score = scores[teams == team].sum()
    print(f"{team}: {total_score}")

# 4. Determine the most consistent performer (lowest score variance)
variances = [scores[players == player].var() for player in unique_players]
most_consistent_index = np.argmin(variances)
print(f"\nMost Consistent Performer: {unique_players[most_consistent_index]} (Variance: {variances[most_consistent_index]:.2f})")


Wins per Team:
Team A: 3
Team B: 2

Player with Highest Average Score: Player 5 (29.00 points)

Total Score by Team:
Team A: 100
Team B: 118

Most Consistent Performer: Player 3 (Variance: 0.00)


---

# NumPy 3D Array Transpose – Easy Problems

---

# Problem 1: Full Axis Permutation
Create a 3D array of shape (2, 3, 4).

• Transpose it so that the shape becomes (4, 2, 3).

• Verify by printing both shapes.

• Check that element [0, 1, 2] in the original corresponds to [2, 0, 1] in the transposed array.

In [ ]:
import numpy as np

In [ ]:
# 1. Create a 3D array of shape (2, 3, 4)
arr1= np.arange(2*3*4).reshape(2,3,4)

print("Original shape:\n", arr1)

# 2. Transpose to shape (4, 2, 3)
# axes order: (2, 0, 1)
arr_t = np.transpose(arr1, (2, 0, 1))
print("Transposed shape:", arr_t.shape)
print()
print("Transposed matrix:", arr_t)

# 3. Verify mapping
orig_val = arr1[0, 1, 2]
trans_val = arr_t[2, 0, 1]
print("\nOriginal [0,1,2] =", orig_val)
print("Transposed [2,0,1] =", trans_val)
print("Check:", orig_val == trans_val)

Original shape:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Transposed shape: (4, 2, 3)

Transposed matrix: [[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]

Original [0,1,2] = 6
Transposed [2,0,1] = 6
Check: True


# Problem 2: From (Batch, Channels, Height, Width) → (Batch, Height, Width, Channels)

In deep learning, images are often stored as (2, 3, 28, 28) → 2 images, 3 channels, 28×28 pixels.

• Transpose it to shape (2, 28, 28, 3).

• Verify the new layout by checking shapes.

• Confirm that element [1, 0, 10, 15] in original moves to [1, 10, 15, 0] in transposed.

In [ ]:
# 1. Create a dummy 4D array (Batch=2, Channels=3, Height=28, Width=28)
arr = np.arange(2*3*28*28).reshape(2, 3, 28, 28)
print("Original shape:", arr.shape)   # (2, 3, 28, 28)

# 2. Transpose to (Batch, Height, Width, Channels)
# axes order: (0, 2, 3, 1)
arr_t = np.transpose(arr, (0, 2, 3, 1))
print("Transposed shape:", arr_t.shape)   # (2, 28, 28, 3)

# 3. Verify mapping of one element
orig_val = arr[1, 0, 10, 15]       # batch=1, channel=0, h=10, w=15
trans_val = arr_t[1, 10, 15, 0]    # same element but moved
print("\nOriginal [1,0,10,15] =", orig_val)
print("Transposed [1,10,15,0] =", trans_val)
print("Check:", orig_val == trans_val)

Original shape: (2, 3, 28, 28)
Transposed shape: (2, 28, 28, 3)

Original [1,0,10,15] = 2647
Transposed [1,10,15,0] = 2647
Check: True


# Problem 3: Transpose Twice

Create a 3D array of shape (3, 4, 5).

• First, transpose it to (5, 3, 4).

• Then transpose the result back to (3, 4, 5) using another transpose.

• Confirm that the final array is identical to the original (np.array_equal).

In [1]:
import numpy as np

In [8]:
# 1. Create a 3D array of shape (3, 4, 5)
arr = np.arange(3*4*5).reshape(3, 4, 5)
print(arr)
print("Original shape:", arr.shape)   # (3, 4, 5)

# 2. First transpose → (5, 3, 4)
arr_t1 = np.transpose(arr, (2, 0, 1))
print("------------------------------------------")
print(arr_t1)
print("After first transpose:", arr_t1.shape)   # (5, 3, 4)

# 3. Transpose back to original → (3, 4, 5)
arr_t2 = np.transpose(arr_t1, (1, 2, 0))
print("------------------------------------------")
print(arr_t2)
print("After second transpose:", arr_t2.shape)   # (3, 4, 5)

# 4. Check equality
print("Arrays identical?", np.array_equal(arr, arr_t2))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
Original shape: (3, 4, 5)
------------------------------------------
[[[ 0  5 10 15]
  [20 25 30 35]
  [40 45 50 55]]

 [[ 1  6 11 16]
  [21 26 31 36]
  [41 46 51 56]]

 [[ 2  7 12 17]
  [22 27 32 37]
  [42 47 52 57]]

 [[ 3  8 13 18]
  [23 28 33 38]
  [43 48 53 58]]

 [[ 4  9 14 19]
  [24 29 34 39]
  [44 49 54 59]]]
After first transpose: (5, 3, 4)
------------------------------------------
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
After second transpose: (3, 4, 5)
Arrays identical? True


# Problem 4: Multi-Step Swap

You have weather data stored as (Years, Months, Days) with shape (2, 12, 30).

- Transpose it so that the shape becomes (30, 12, 2) → days first, years last.

- Find the value at [year=1, month=5, day=10] in the original and confirm its new position in the
transposed array.

In [ ]:
# 1. Create weather data array
data = np.arange(2*12*30).reshape(2, 12, 30)
print("Original shape:", data.shape)   # (2, 12, 30)

# 2. Transpose to (Days, Months, Years)
data_t = np.transpose(data, (2, 1, 0))
print("Transposed shape:", data_t.shape)   # (30, 12, 2)

# 3. Pick element [year=1, month=5, day=10]
original_value = data[1, 5, 10]
print("\nOriginal value:", original_value)

# 4. New position after transpose → [day=10, month=5, year=1]
new_value = data_t[10, 5, 1]
print("New value (transposed):", new_value)

# 5. Confirm both match
print("Match?", original_value == new_value)

Original shape: (2, 12, 30)
Transposed shape: (30, 12, 2)

Original value: 520
New value (transposed): 520
Match? True


# Problem 5: Combining Transpose with Reshape

Create a 3D array of shape (2, 3, 4).

• First, transpose it to (3, 2, 4).

• Then reshape the result into a 2D array of shape (6, 4).

• Print both intermediate and final shapes.

• Verify that the reshaping preserves the total number of elements.

In [9]:
# 1. Create a 3D array of shape (2, 3, 4)
arr = np.arange(2*3*4).reshape(2, 3, 4)
print("Original shape:", arr.shape)
print(arr)   # (2, 3, 4)

# 2. Transpose to (3, 2, 4)
arr_t = np.transpose(arr, (1, 0, 2))
print("After transpose:", arr_t.shape)
print(arr_t)

arr_t1 = np.transpose(arr_t, (0,1,2))
print("After transpose:", arr_t1.shape)
print(arr_t1)  # (3, 2, 4)

# 3. Reshape to (6, 4)
arr_r = arr_t.reshape(6, 4)
print("After reshape:", arr_r.shape)
print(arr_r)   # (6, 4)

# 4. Verify total elements are preserved
print("Elements count preserved?", arr.size == arr_r.size)

Original shape: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
After transpose: (3, 2, 4)
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
After transpose: (3, 2, 4)
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
After reshape: (6, 4)
[[ 0  1  2  3]
 [12 13 14 15]
 [ 4  5  6  7]
 [16 17 18 19]
 [ 8  9 10 11]
 [20 21 22 23]]
Elements count preserved? True


---
# NumPy Transpose Problems with 3D Arrays (Use Case Based)

---

Problem 1: Medical Imaging Data

A hospital stores MRI scans in the format (patients, slices, pixels).

- Create a NumPy array of shape (2, 4, 5) representing 2 patients, each with 4 slices of size 5 pixels.

- Transpose the data so that the shape becomes (4, 2, 5) → now each slice groups data from both patients.

- Verify the new shape and check where element [patient=1, slice=2, pixel=3] is located in the new layout.

In [ ]:
import numpy as np

# Step 1: Create a 3D array
# Shape: (2 patients, 4 slices, 5 pixels per slice)
data = np.arange(2 * 4 * 5).reshape(2, 4, 5)
print("Original Data:\n", data)
print("\nOriginal Shape:", data.shape)  # (2, 4, 5)

# Step 2: Transpose the array to group by slices first
# Desired new shape: (4 slices, 2 patients, 5 pixels)
transposed_data = data.transpose(1, 0, 2)
print("\nTransposed Data:\n", transposed_data)
print("\nNew Shape:", transposed_data.shape)  # (4, 2, 5)

# Step 3: Verify where element [patient=1, slice=2, pixel=3] goes
patient_idx = 1
slice_idx = 2
pixel_idx = 3

original_value = data[patient_idx, slice_idx, pixel_idx]
print(f"\nOriginal Value at [Patient={patient_idx}, Slice={slice_idx}, Pixel={pixel_idx}] = {original_value}")

# After transpose, this element should now be at [Slice, Patient, Pixel]
new_position_value = transposed_data[slice_idx, patient_idx, pixel_idx]
print(f"Value at New Position [Slice={slice_idx}, Patient={patient_idx}, Pixel={pixel_idx}] = {new_position_value}")

# Step 4: Verify correctness
if original_value == new_position_value:
    print("\nVerification Successful: Element is correctly transposed!")
else:
    print("\nVerification Failed: Element not in expected location.")


Original Data:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]

Original Shape: (2, 4, 5)

Transposed Data:
 [[[ 0  1  2  3  4]
  [20 21 22 23 24]]

 [[ 5  6  7  8  9]
  [25 26 27 28 29]]

 [[10 11 12 13 14]
  [30 31 32 33 34]]

 [[15 16 17 18 19]
  [35 36 37 38 39]]]

New Shape: (4, 2, 5)

Original Value at [Patient=1, Slice=2, Pixel=3] = 33
Value at New Position [Slice=2, Patient=1, Pixel=3] = 33

Verification Successful: Element is correctly transposed!


Problem 2: Video Frame Data

A video dataset is stored in the format (frames, height, width).

• Create a NumPy array of shape (6, 3, 4) → 6 frames, each with 3x4 pixels.

• Transpose it to (3, 4, 6) → now each pixel position shows its value across all frames.

• Verify that frame-wise data is correctly rearranged by checking positions before and after transpose

In [ ]:
import numpy as np

# Step 1: Create a 3D array
# Shape: (6 frames, 3 height, 4 width)
video_data = np.arange(6 * 3 * 4).reshape(6, 3, 4)
print("Original Video Data:\n", video_data)
print("\nOriginal Shape:", video_data.shape)  # (6, 3, 4)

# Step 2: Transpose to rearrange by pixel position
# Desired new shape: (3 height, 4 width, 6 frames)
transposed_video = video_data.transpose(1, 2, 0)
print("\nTransposed Video Data:\n", transposed_video)
print("\nNew Shape:", transposed_video.shape)  # (3, 4, 6)

# Step 3: Verify correctness
# Pick a specific position to track
frame_idx = 4   # 5th frame (index starts at 0)
row_idx = 1     # 2nd row
col_idx = 2     # 3rd column

# Original position
original_value = video_data[frame_idx, row_idx, col_idx]
print(f"\nOriginal Value at [Frame={frame_idx}, Row={row_idx}, Col={col_idx}] = {original_value}")

# After transpose:
# The new position will be [Row, Col, Frame]
new_position_value = transposed_video[row_idx, col_idx, frame_idx]
print(f"Value at New Position [Row={row_idx}, Col={col_idx}, Frame={frame_idx}] = {new_position_value}")

# Verification check
if original_value == new_position_value:
    print("\nVerification Successful: Frame-wise data correctly transposed!")
else:
    print("\nVerification Failed: Data mismatch after transpose.")


Original Video Data:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[60 61 62 63]
  [64 65 66 67]
  [68 69 70 71]]]

Original Shape: (6, 3, 4)

Transposed Video Data:
 [[[ 0 12 24 36 48 60]
  [ 1 13 25 37 49 61]
  [ 2 14 26 38 50 62]
  [ 3 15 27 39 51 63]]

 [[ 4 16 28 40 52 64]
  [ 5 17 29 41 53 65]
  [ 6 18 30 42 54 66]
  [ 7 19 31 43 55 67]]

 [[ 8 20 32 44 56 68]
  [ 9 21 33 45 57 69]
  [10 22 34 46 58 70]
  [11 23 35 47 59 71]]]

New Shape: (3, 4, 6)

Original Value at [Frame=4, Row=1, Col=2] = 54
Value at New Position [Row=1, Col=2, Frame=4] = 54

Verification Successful: Frame-wise data correctly transposed!


Problem 3: IoT Sensor Data

A smart building records temperature with 3 sensors every hour for 2 days. Data is stored as (days, hours, sensors).

• Create a NumPy array of shape (2, 4, 3) → 2 days, 4 hours/day, 3 sensors.

• Transpose it to (3, 2, 4) so that the first axis corresponds to sensors making analysis sensor-wise.

• Verify the mapping of element [day=1, hour=2, sensor=0].

In [ ]:
import numpy as np

# Step 1: Create a 3D array
# Shape: (2 days, 4 hours/day, 3 sensors)
iot_data = np.arange(2 * 4 * 3).reshape(2, 4, 3)
print("Original IoT Sensor Data:\n", iot_data)
print("\nOriginal Shape:", iot_data.shape)  # (2, 4, 3)

# Step 2: Transpose the array for sensor-wise analysis
# Desired shape: (3 sensors, 2 days, 4 hours)
transposed_data = iot_data.transpose(2, 0, 1)
print("\nTransposed IoT Sensor Data:\n", transposed_data)
print("\nNew Shape:", transposed_data.shape)  # (3, 2, 4)

# Step 3: Verify a specific element mapping
day_idx = 1     # Day 2 (index starts at 0)
hour_idx = 2    # Hour 3
sensor_idx = 0  # Sensor 1

# Value in original array
original_value = iot_data[day_idx, hour_idx, sensor_idx]
print(f"\nOriginal Value at [Day={day_idx}, Hour={hour_idx}, Sensor={sensor_idx}] = {original_value}")

# After transpose, position changes to [Sensor, Day, Hour]
new_position_value = transposed_data[sensor_idx, day_idx, hour_idx]
print(f"Value at New Position [Sensor={sensor_idx}, Day={day_idx}, Hour={hour_idx}] = {new_position_value}")

# Step 4: Verification
if original_value == new_position_value:
    print("\nVerification Successful: Element correctly mapped after transpose!")
else:
    print("\nVerification Failed: Data mismatch after transpose.")


Original IoT Sensor Data:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]

Original Shape: (2, 4, 3)

Transposed IoT Sensor Data:
 [[[ 0  3  6  9]
  [12 15 18 21]]

 [[ 1  4  7 10]
  [13 16 19 22]]

 [[ 2  5  8 11]
  [14 17 20 23]]]

New Shape: (3, 2, 4)

Original Value at [Day=1, Hour=2, Sensor=0] = 18
Value at New Position [Sensor=0, Day=1, Hour=2] = 18

Verification Successful: Element correctly mapped after transpose!


Problem 4: Sports Team Performance

A league records match statistics for 2 teams across 3 matches, tracking 4 performance metrics per match.

Data is stored as (teams, matches, metrics).

• Create a NumPy array of shape (2, 3, 4).

• Transpose it to (3, 2, 4) → now each match groups the performance of both teams.

• Confirm where the stats of Team 1, Match 2, Metric 3 go in the new layout.


In [ ]:
import numpy as np

# Step 1: Create a 3D array
# Shape: (2 teams, 3 matches, 4 metrics)
data = np.arange(2 * 3 * 4).reshape(2, 3, 4)
print("Original Sports Data:\n", data)
print("\nOriginal Shape:", data.shape)  # (2, 3, 4)

# Step 2: Transpose to group by matches
# Desired shape: (3 matches, 2 teams, 4 metrics)
transposed_data = data.transpose(1, 0, 2)
print("\nTransposed Sports Data:\n", transposed_data)
print("\nNew Shape:", transposed_data.shape)  # (3, 2, 4)

# Step 3: Verify element mapping
team_idx = 1     # Team 1 (index starts at 0, so Team 2 is index 1)
match_idx = 2    # Match 2 (index starts at 0, so Match 3 is index 2)
metric_idx = 3   # Metric 3 (index starts at 0, so Metric 4 is index 3)

# Original location
original_value = data[team_idx, match_idx, metric_idx]
print(f"\nOriginal Value at [Team={team_idx}, Match={match_idx}, Metric={metric_idx}] = {original_value}")

# After transpose, the indexing changes:
# Now it's [Match, Team, Metric]
new_value = transposed_data[match_idx, team_idx, metric_idx]
print(f"Value at New Position [Match={match_idx}, Team={team_idx}, Metric={metric_idx}] = {new_value}")

# Step 4: Verification
if original_value == new_value:
    print("\nVerification Successful: Element correctly mapped after transpose!")
else:
    print("\nVerification Failed: Data mismatch after transpose.")


Original Sports Data:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Original Shape: (2, 3, 4)

Transposed Sports Data:
 [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]

New Shape: (3, 2, 4)

Original Value at [Team=1, Match=2, Metric=3] = 23
Value at New Position [Match=2, Team=1, Metric=3] = 23

Verification Successful: Element correctly mapped after transpose!


Problem 5: Climate Data

A research project stores temperature readings for 2 years, each with 3 months, and 5 cities. Format: (years, months, cities).

• Create a NumPy array of shape (2, 3, 5).

• Transpose it to (5, 2, 3) → so each city has its own block of data across years and months.

• Check that the total number of elements remains the same after transpose.


In [ ]:
import numpy as np

# Step 1: Create the climate data array
# Shape: (2 years, 3 months, 5 cities)
data = np.arange(2 * 3 * 5).reshape(2, 3, 5)
print("Original Climate Data:\n", data)
print("\nOriginal Shape:", data.shape)  # (2, 3, 5)

# Step 2: Transpose to group by cities
# Desired shape: (5 cities, 2 years, 3 months)
transposed_data = data.transpose(2, 0, 1)
print("\nTransposed Climate Data:\n", transposed_data)
print("\nNew Shape:", transposed_data.shape)  # (5, 2, 3)

# Step 3: Verify total number of elements remains the same
original_count = data.size
transposed_count = transposed_data.size
print(f"\nTotal Elements in Original: {original_count}")
print(f"Total Elements in Transposed: {transposed_count}")

# Verification
if original_count == transposed_count:
    print("\nVerification Successful: Number of elements remains unchanged!")
else:
    print("\nVerification Failed: Data mismatch after transpose.")


Original Climate Data:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]

Original Shape: (2, 3, 5)

Transposed Climate Data:
 [[[ 0  5 10]
  [15 20 25]]

 [[ 1  6 11]
  [16 21 26]]

 [[ 2  7 12]
  [17 22 27]]

 [[ 3  8 13]
  [18 23 28]]

 [[ 4  9 14]
  [19 24 29]]]

New Shape: (5, 2, 3)

Total Elements in Original: 30
Total Elements in Transposed: 30

Verification Successful: Number of elements remains unchanged!


# NumPy Fancy Indexing Problems (1D, 2D, 3D)

# Problem 1: Stock Prices
Create a 1D NumPy array of 30 stock prices.

• Extract the prices on prime-numbered days.

• Find the top 5 highest prices using fancy indexing.


In [ ]:
# 1. Create a 1D array of 30 stock prices (dummy values for example)
prices = np.random.randint(100, 500, size=30)
print("Stock Prices (30 days):\n", prices)

# 2. Extract prices on prime-numbered days (indexing from day=1 to 30)
# First, define prime numbers up to 30
prime_days = np.array([2,3,5,7,11,13,17,19,23,29]) - 1
prime_day_prices = prices[prime_days]
print("Prices on prime-numbered days:", prime_day_prices)

# 3. Find the top 5 highest prices using fancy indexing
top5_indices = np.argsort(prices)[-5:]   # last 5 after sorting
top5_prices = prices[top5_indices]
print("\nTop 5 highest prices:\n", top5_prices)

Stock Prices (30 days):
 [476 288 406 327 244 121 322 304 415 491 274 235 181 399 268 366 231 466
 337 451 355 497 371 496 205 105 288 436 271 101]
Prices on prime-numbered days: [288 406 244 322 274 181 231 337 371 271]

Top 5 highest prices:
 [466 476 491 496 497]


# Problem 2: Exam Scores

Generate a 1D array of 50 student scores (0–100).

• Extract the scores of the top 10 students (highest scores).

• Replace scores below 40 with -1 using fancy indexing.




In [ ]:
# 1. Generate a 1D array of 50 student scores (0–100)
scores = np.random.randint(0, 101, size=50)
print("Original Scores:\n", scores)

# 2. Extract top 10 students (highest scores)
top10_idx = np.argsort(scores)[-10:]   # indices of top 10
top10_scores = scores[top10_idx]
print("\nTop 10 Scores:\n", top10_scores)

# 3. Replace scores below 40 with -1 using fancy indexing
low_scores_idx = np.where(scores < 40)
scores[low_scores_idx] = -1
print("\nScores after replacing <40 with -1:\n", scores)

Original Scores:
 [ 89  12  89  20   7  65  11  40   3  36  10  90   5   1  72  61  38  11
  24  63  47  23  78  70  48   1   3  59  68  84  84  80  35  95  82   2
  30  91  94  25  95  57  74  58   7  33  90  16  46 100]

Top 10 Scores:
 [ 84  89  89  90  90  91  94  95  95 100]

Scores after replacing <40 with -1:
 [ 89  -1  89  -1  -1  65  -1  40  -1  -1  -1  90  -1  -1  72  61  -1  -1
  -1  63  47  -1  78  70  48  -1  -1  59  68  84  84  80  -1  95  82  -1
  -1  91  94  -1  95  57  74  58  -1  -1  90  -1  46 100]


# Problem 3: Sensor Fault Detection

Create a 1D array of 100 sensor readings (random floats).

• Find all indices where values are above mean + 1 std deviation.

• Extract those faulty readings using fancy indexing.




In [ ]:
# 1. Create a 1D array of 100 sensor readings (random floats)
readings = np.random.normal(loc=50, scale=10, size=100)  # mean=50, std=10
print("Sensor Readings:\n", readings)

# 2. Compute mean and standard deviation
mean = readings.mean()
std = readings.std()
threshold = mean + std
print("\nMean:", mean, " Std Dev:", std, " Threshold:", threshold)

# 3. Find indices where values > mean + 1 std deviation
faulty_idx = np.where(readings > threshold)[0]
print("\nFaulty Indices:\n", faulty_idx)

# 4. Extract faulty readings using fancy indexing
faulty_readings = readings[faulty_idx]
print("\nFaulty Readings:\n", faulty_readings)

Sensor Readings:
 [57.30073494 61.6680897  66.4217673  44.71090814 34.05436423 50.61162109
 53.33891304 48.21005314 50.77429671 72.41160127 47.58238566 34.40763961
 51.21384164 49.99886639 42.77478493 50.69938812 51.0287034  44.29312153
 54.17542552 50.22398305 29.46851534 40.58792022 39.57290115 44.61029215
 40.6824096  50.69214204 47.54924596 60.50517392 51.84377413 50.22461489
 52.44163782 40.41729916 63.55581043 42.71102787 53.91403522 65.88990702
 51.81550382 61.53780389 71.33804059 75.56015167 42.47220251 35.13351491
 38.71503187 64.11490792 54.85909033 55.86089305 55.45301005 54.54082037
 60.45137846 51.61647753 39.94393962 40.98951906 46.18305922 68.93583744
 41.90070696 44.24659893 40.42514181 58.13921503 35.53305141 44.03812921
 44.97789333 68.29568741 60.41681211 40.43487565 54.1357527  46.17343287
 39.01632363 52.44344535 45.31921677 56.79291418 55.38266625 46.14678256
 49.66574076 33.26324819 33.97963559 72.4430359  46.87952473 53.71367494
 29.21236809 58.87110745 48.83771

# Problem 4: DNA Sequence Encoding

Represent a DNA sequence (A=0, C=1, G=2, T=3) as a 1D NumPy array of length 20.

• Extract all occurrences of G and T.

• Replace all A with -1 using fancy indexing.




In [ ]:
# 1. Encode DNA sequence (length 20, values A=0, C=1, G=2, T=3)
dna = np.random.randint(0, 4, size=20)
print("Original DNA sequence (0=A,1=C,2=G,3=T):\n", dna)

# 2. Extract all occurrences of G (2) and T (3)
gt_idx = np.where((dna == 2) | (dna == 3))
gt_bases = dna[gt_idx]
print("\nOccurrences of G and T:\n", gt_bases)

# 3. Replace all A (0) with -1
a_idx = np.where(dna == 0)
dna[a_idx] = -1
print("\nDNA sequence after replacing A with -1:\n", dna)

Original DNA sequence (0=A,1=C,2=G,3=T):
 [2 2 3 2 0 1 3 0 3 2 0 0 2 1 2 2 3 3 1 3]

Occurrences of G and T:
 [2 2 3 2 3 3 2 2 2 2 3 3 3]

DNA sequence after replacing A with -1:
 [ 2  2  3  2 -1  1  3 -1  3  2 -1 -1  2  1  2  2  3  3  1  3]


# Problem 5: Employee Salaries

Create a 1D array of 20 salaries.

• Extract salaries of employees whose index is in [2, 5, 7, 11, 15].

• Give a 10% raise only to these extracted salaries using fancy indexing.


In [ ]:
import numpy as np

# 1. Create a 1D array of 20 salaries (random between 30k and 100k)
salaries = np.random.randint(30000, 100001, size=20)
print("Original Salaries:\n", salaries)

# 2. Extract salaries at specific indices [2, 5, 7, 11, 15]
indices = np.array([2, 5, 7, 11, 15])
selected_salaries = salaries[indices]
print("\nSelected Salaries:\n", selected_salaries)

# 3. Give 10% raise only to these salaries
salaries[indices] = salaries[indices] * 1.10
print("\nUpdated Salaries after 10% raise:\n", salaries)

Original Salaries:
 [41976 84238 55609 63367 97056 73582 39991 49786 45418 64721 91505 43255
 50292 46882 87861 69625 95098 69800 79650 75946]

Selected Salaries:
 [55609 73582 49786 43255 69625]

Updated Salaries after 10% raise:
 [41976 84238 61169 63367 97056 80940 39991 54764 45418 64721 91505 47580
 50292 46882 87861 76587 95098 69800 79650 75946]


# 2D Array Use Cases
Problem 6: Matrix Row/Column Extraction

Create a 6x6 matrix of integers from 1 to 36.

• Extract all elements from rows [1, 3, 5] and columns [0, 2, 4] using fancy indexing.


In [ ]:
# Create a 6x6 matrix with integers from 1 to 36
matrix = np.arange(1, 37).reshape(6, 6)
print("Original 6x6 Matrix:\n", matrix)

# Define rows and columns to extract
rows = [1, 3, 5]
cols = [0, 2, 4]

# Use fancy indexing to extract elements
extracted = matrix[rows][:, cols]
print("\nExtracted Elements (Rows [1,3,5] & Columns [0,2,4]):\n", extracted)


Original 6x6 Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Extracted Elements (Rows [1,3,5] & Columns [0,2,4]):
 [[ 7  9 11]
 [19 21 23]
 [31 33 35]]


Problem 7: Student Marks Table

Generate a 10x5 array representing 10 students and 5 subjects.

• Extract marks of students [2, 4, 6, 8] in subjects [1, 3].

• Replace all marks below 30 with 0 for these students.

In [ ]:
import numpy as np

# Generate a 10x5 array representing 10 students and 5 subjects
# Marks are randomly generated between 20 and 100
np.random.seed(42)
marks = np.random.randint(20, 101, size=(10, 5))
print("Original Marks Table:\n", marks)

# Convert students and subjects to numpy arrays
students = np.array([2, 4, 6, 8])
subjects = np.array([1, 3])

# Extract marks using fancy indexing
selected_marks = marks[students][:, subjects]
print("\nSelected Students & Subjects Marks:\n", selected_marks)

# Replace marks below 30 with 0 for these students and subjects
marks[students[:, None], subjects] = np.where(
    marks[students[:, None], subjects] < 30,
    0,
    marks[students[:, None], subjects]
)

print("\nUpdated Marks Table (Marks below 30 replaced with 0 for selected students and subjects):\n", marks)


Original Marks Table:
 [[71 34 91 80 40]
 [94 94 43 22 41]
 [72 21 49 57 21]
 [83 79 40 52 95]
 [77 41 68 78 61]
 [79 99 34 81 81]
 [66 81 70 74 83]
 [22 70 26 40 92]
 [58 37 23 79 33]
 [28 72 21 79 90]]

Selected Students & Subjects Marks:
 [[21 57]
 [41 78]
 [81 74]
 [37 79]]

Updated Marks Table (Marks below 30 replaced with 0 for selected students and subjects):
 [[71 34 91 80 40]
 [94 94 43 22 41]
 [72  0 49 57 21]
 [83 79 40 52 95]
 [77 41 68 78 61]
 [79 99 34 81 81]
 [66 81 70 74 83]
 [22 70 26 40 92]
 [58 37 23 79 33]
 [28 72 21 79 90]]


Problem 8: Airline Seat Booking

Create a 12x6 seating matrix (rows × columns).

• Extract all aisle seats (first and last column).

• Mark seats [row=2, cols=[1,2,4]] as booked (-1) using fancy indexing

In [ ]:
import numpy as np

# Create a 12x6 seating matrix
# Let's represent each seat with its seat number starting from 1
seats = np.arange(1, 12 * 6 + 1).reshape(12, 6)
print("Original Seating Layout:\n", seats)

# Extract all aisle seats (first and last column)
# Aisle seats are in columns 0 and 5
aisle_seats = seats[:, [0, 5]]
print("\nAisle Seats (Columns 0 and 5):\n", aisle_seats)

# Mark specific seats as booked (-1) using fancy indexing
# Booking seats in row=2 (3rd row), columns [1, 2, 4]
row_to_book = 2
cols_to_book = np.array([1, 2, 4])

seats[row_to_book, cols_to_book] = -1

print("\nUpdated Seating Layout (Booked seats marked as -1):\n", seats)


Original Seating Layout:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]
 [61 62 63 64 65 66]
 [67 68 69 70 71 72]]

Aisle Seats (Columns 0 and 5):
 [[ 1  6]
 [ 7 12]
 [13 18]
 [19 24]
 [25 30]
 [31 36]
 [37 42]
 [43 48]
 [49 54]
 [55 60]
 [61 66]
 [67 72]]

Updated Seating Layout (Booked seats marked as -1):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 -1 -1 16 -1 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]
 [61 62 63 64 65 66]
 [67 68 69 70 71 72]]


Problem 9: Chessboard Pattern

Create an 8x8 matrix with values from 0–63.

• Extract all black squares (even row + odd column, odd row + even column).

• Replace them with -1.


In [ ]:
import numpy as np

# Create an 8x8 matrix with values from 0 to 63
chessboard = np.arange(64).reshape(8, 8)
print("Original Chessboard:\n", chessboard)

# Identify black squares
# Black squares are at positions:
# (even row + odd column) OR (odd row + even column)
rows = np.arange(8)[:, None]
cols = np.arange(8)

# Create a mask for black squares
black_squares_mask = ((rows % 2 == 0) & (cols % 2 == 1)) | ((rows % 2 == 1) & (cols % 2 == 0))

# Replace black squares with -1
chessboard[black_squares_mask] = -1

# Display updated chessboard
print("\nUpdated Chessboard (Black squares replaced with -1):\n", chessboard)


Original Chessboard:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]

Updated Chessboard (Black squares replaced with -1):
 [[ 0 -1  2 -1  4 -1  6 -1]
 [-1  9 -1 11 -1 13 -1 15]
 [16 -1 18 -1 20 -1 22 -1]
 [-1 25 -1 27 -1 29 -1 31]
 [32 -1 34 -1 36 -1 38 -1]
 [-1 41 -1 43 -1 45 -1 47]
 [48 -1 50 -1 52 -1 54 -1]
 [-1 57 -1 59 -1 61 -1 63]]


Problem 10: Product Sales Data

Create a 5x7 array representing sales of 5 products over 7 days.

• Extract sales of products [1, 3] on days [2, 4, 6].

• Increase those extracted values by 20%.

In [ ]:
import numpy as np

# Create a 5x7 array as float type
sales = np.random.randint(50, 200, size=(5, 7)).astype(float)
print("Original Sales Data:\n", sales)

# Define products and days
products = [1, 3]
days = [2, 4, 6]

# Extract specific product and day sales
extracted_sales = sales[np.ix_(products, days)]
print("\nExtracted Sales (Products 1 & 3, Days 2, 4 & 6):\n", extracted_sales)

# Increase values by 20% in place
sales[np.ix_(products, days)] *= 1.20

# Final updated data
print("\nUpdated Sales Data (After 20% Increase):\n", sales)


Original Sales Data:
 [[ 57.  84. 130.  99. 153. 181.  51.]
 [183. 103. 155.  53. 103. 195.  93.]
 [ 63. 144.  97.  64.  89. 131. 160.]
 [102.  73. 173.  90.  64.  94. 114.]
 [138. 120.  58. 137. 178. 185. 112.]]

Extracted Sales (Products 1 & 3, Days 2, 4 & 6):
 [[155. 103.  93.]
 [173.  64. 114.]]

Updated Sales Data (After 20% Increase):
 [[ 57.   84.  130.   99.  153.  181.   51. ]
 [183.  103.  186.   53.  123.6 195.  111.6]
 [ 63.  144.   97.   64.   89.  131.  160. ]
 [102.   73.  207.6  90.   76.8  94.  136.8]
 [138.  120.   58.  137.  178.  185.  112. ]]


# 3D Array Use Cases

# Problem 11: Video Frames (RGB)

Create a 4x3x3 array representing 4 frames, each 3x3 pixel.

• Extract the center pixel from each frame using fancy indexing.


In [ ]:
import numpy as np

# 1. Create a 4x3x3 array (4 frames, each 3x3 pixels)
frames = np.arange(4*3*3).reshape(4, 3, 3)
print("Video Frames (4 frames of 3x3):\n", frames)

# 2. Extract the center pixel (row=1, col=1) from each frame
center_pixels = frames[:, 1, 1]
print("\nCenter pixel from each frame:\n", center_pixels)


Video Frames (4 frames of 3x3):
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]]

Center pixel from each frame:
 [ 4 13 22 31]


# Problem 12: Weather Data

Create a (2, 12, 30) array → 2 years, 12 months, 30 days.

• Extract temperatures of months [0, 5, 11] for year 1 on days [10, 20].


In [ ]:
import numpy as np

# 1. Create weather data: (2 years, 12 months, 30 days)
weather = np.random.randint(15, 40, size=(2, 12, 30))  # random temps between 15–40
print("Weather data shape:", weather.shape)  # (2, 12, 30)

# 2. Extract for year=1 (2nd year → index 1), months [0, 5, 11], days [10, 20]
result = weather[1, [0, 5, 11], :][:, [10, 20]]

print("\nTemperatures for year=1, months [0,5,11], days [10,20]:\n", result)


Weather data shape: (2, 12, 30)

Temperatures for year=1, months [0,5,11], days [10,20]:
 [[21 39]
 [21 23]
 [15 32]]


# Problem 13: Hospital Patient Records

Create a (3, 4, 5) array → 3 patients, 4 days, 5 test results/day.

• Extract test results of patients [0, 2] on day 3 for tests [1, 3].

In [ ]:
import numpy as np

# 1. Create patient records: (3 patients, 4 days, 5 tests/day)
records = np.random.randint(50, 150, size=(3, 4, 5))  # random test results
print("Records shape:", records.shape)  # (3, 4, 5)

# 2. Extract test results for patients [0, 2], day=3 (index 2), tests [1, 3]
result = records[[0, 2], 2, :][:, [1, 3]]

print("\nExtracted test results:\n", result)


Records shape: (3, 4, 5)

Extracted test results:
 [[ 99 131]
 [ 65  53]]


# Problem 14: Sports Team Analytics

Create a (5, 6, 4) array → 5 teams, 6 matches, 4 stats each.

• Extract stats of teams [1, 3, 4] for matches [2, 5].

In [ ]:
import numpy as np

# 1. Create sports data: 5 teams, 6 matches, 4 stats each
data = np.random.randint(0, 100, size=(5, 6, 4))
print("Data shape:", data.shape)  # (5, 6, 4)

# 2. Extract stats of teams [1, 3, 4] for matches [2, 5]
result = data[[1, 3, 4], :][:, [2, 5], :]

print("\nExtracted stats (teams [1,3,4], matches [2,5]):\n", result)
print("Result shape:", result.shape)


Data shape: (5, 6, 4)

Extracted stats (teams [1,3,4], matches [2,5]):
 [[[93 62 47 60]
  [46 55 85 13]]

 [[67  9 66 17]
  [ 5 51 25 63]]

 [[20 69 69  3]
  [ 8  2 30 39]]]
Result shape: (3, 2, 4)


# Problem 15: Movie Ratings

Create a (10, 5, 4) array → 10 movies, 5 critics, 4 rating categories.

• Extract ratings of movies [2, 4, 7] by critics [1, 3] in categories [0, 2].

In [ ]:
import numpy as np

# 1. Create ratings data: 10 movies, 5 critics, 4 categories
ratings = np.random.randint(1, 11, size=(10, 5, 4))  # ratings 1–10
print("Ratings shape:", ratings.shape)  # (10, 5, 4)

# 2. Extract ratings for movies [2, 4, 7], critics [1, 3], categories [0, 2]
result = ratings[[2, 4, 7]][:, [1, 3]][:, :, [0, 2]]

print("\nExtracted ratings (movies [2,4,7], critics [1,3], categories [0,2]):\n", result)
print("Result shape:", result.shape)


Ratings shape: (10, 5, 4)

Extracted ratings (movies [2,4,7], critics [1,3], categories [0,2]):
 [[[10  6]
  [ 1  5]]

 [[ 6  3]
  [ 3  3]]

 [[ 9  8]
  [ 5  2]]]
Result shape: (3, 2, 2)


# Problem 16: IoT Device Monitoring

Create a (3, 24, 7) array → 3 devices, 24 hours, 7 days.

• Extract hourly readings for devices [0, 2] on days [1, 3, 5].

In [ ]:
import numpy as np

# 1. Create IoT data: 3 devices, 24 hours, 7 days
iot_data = np.random.randint(0, 100, size=(3, 24, 7))
print("IoT data shape:", iot_data.shape)  # (3, 24, 7)

# 2. Extract hourly readings for devices [0, 2] on days [1, 3, 5]
result = iot_data[[0, 2], :, :][:, :, [1, 3, 5]]

print("\nExtracted readings (devices [0,2], all 24 hours, days [1,3,5]):\n", result)
print("Result shape:", result.shape)


IoT data shape: (3, 24, 7)

Extracted readings (devices [0,2], all 24 hours, days [1,3,5]):
 [[[ 6 90 90]
  [58 53 24]
  [69 32 28]
  [25 84 70]
  [48 85 62]
  [70 95 93]
  [55 61 29]
  [44 29 39]
  [ 0 46 91]
  [50  3  7]
  [ 2  9 82]
  [86 91 49]
  [ 7 56 87]
  [71 66 96]
  [33 95 77]
  [15 36 84]
  [54 81 73]
  [22 18 35]
  [81  0 68]
  [ 1 86 19]
  [37  8 52]
  [85 80 29]
  [95 80  8]
  [24 21 25]]

 [[24 81 15]
  [54 41 29]
  [17 95 38]
  [61 61 15]
  [29 83 64]
  [ 2 13 67]
  [36 47 52]
  [14 87 11]
  [60 69 55]
  [87 61 97]
  [51 58 19]
  [53 97 89]
  [ 5  4 46]
  [ 8 19 34]
  [61 87 31]
  [88 67 97]
  [66 28 66]
  [75  8 39]
  [10 97 78]
  [ 4 89 69]
  [47 27 76]
  [44 61 57]
  [39 39 76]
  [87 79 91]]]
Result shape: (2, 24, 3)


# Problem 17: Retail Store Inventory

Create a (4, 10, 6) array → 4 stores, 10 products, 6 months.

• Extract data for stores [1, 3], products [2, 5, 7], and months [0, 2, 4].

In [ ]:
import numpy as np

# 1. Create inventory data: 4 stores, 10 products, 6 months
inventory = np.random.randint(50, 500, size=(4, 10, 6))
print("Inventory shape:", inventory.shape)  # (4, 10, 6)

# 2. Extract for stores [1, 3], products [2, 5, 7], months [0, 2, 4]
result = inventory[[1, 3]][:, [2, 5, 7]][:, :, [0, 2, 4]]

print("\nExtracted inventory data:\n", result)
print("Result shape:", result.shape)


Inventory shape: (4, 10, 6)

Extracted inventory data:
 [[[241  61 450]
  [300 485  56]
  [484  75 275]]

 [[263 435 121]
  [ 60 266 151]
  [450 426 209]]]
Result shape: (2, 3, 3)


# Problem 18: Scientific Experiment

Create a (2, 5, 8) array → 2 trials, 5 experiments, 8 observations each.

• Extract trial 1 results for experiments [1, 4] at observations [2, 5, 7].


In [ ]:
import numpy as np

# 1. Create experiment data: 2 trials, 5 experiments, 8 observations
data = np.random.randint(0, 100, size=(2, 5, 8))
print("Data shape:", data.shape)  # (2, 5, 8)

# 2. Extract trial 1 results (index=0) for experiments [1, 4] and observations [2, 5, 7]
result = data[0, [1, 4]][:, [2, 5, 7]]

print("\nExtracted results (trial 1, experiments [1,4], obs [2,5,7]):\n", result)
print("Result shape:", result.shape)


Data shape: (2, 5, 8)

Extracted results (trial 1, experiments [1,4], obs [2,5,7]):
 [[45 43 74]
 [74  3 57]]
Result shape: (2, 3)


# Problem 19: E-commerce Orders

Create a (6, 4, 3) array → 6 customers, 4 orders each, 3 features/order.

• Extract features of customers [0, 2, 5] for orders [1, 3].


In [ ]:
import numpy as np

# 1. Create dummy order data
orders = np.random.randint(1, 100, size=(6, 4, 3))
print("Orders shape:", orders.shape)  # (6, 4, 3)

# 2. Extract features for customers [0,2,5] and orders [1,3]
result = orders[[0,2,5]][:, [1,3], :]

print("\nExtracted features (customers [0,2,5], orders [1,3]):\n", result)
print("Result shape:", result.shape)


Orders shape: (6, 4, 3)

Extracted features (customers [0,2,5], orders [1,3]):
 [[[97  7 76]
  [31 58 61]]

 [[79 34 36]
  [58 12  3]]

 [[89 28 66]
  [40 76 56]]]
Result shape: (3, 2, 3)


# Problem 20: Image Dataset

Create a (5, 28, 28) array → 5 grayscale images of 28×28 pixels.

Extract the corner pixels (top-left, top-right, bottom-left, bottom-right) from each image using fancy indexing.


In [ ]:
# 1. Create dummy images: 5 grayscale images 28x28
images = np.random.randint(0, 256, size=(5, 28, 28))
print("Images shape:", images.shape)  # (5, 28, 28)

# 2. Extract corner pixels for each image
# corners: top-left (0,0), top-right (0,27), bottom-left (27,0), bottom-right (27,27)
corner_pixels = images[:, [0,0,27,27], [0,27,0,27]]

print("\nCorner pixels of each image:\n", corner_pixels)
print("Corner pixels shape:", corner_pixels.shape)


Images shape: (5, 28, 28)

Corner pixels of each image:
 [[163 211 111   9]
 [241 100  50 155]
 [ 46 141  74 193]
 [217  20  47 150]
 [121  64 126   7]]
Corner pixels shape: (5, 4)


# Detective Case Study: The Mystery of the Stolen Diamonds


Scene 1: The Crime Scene

Detective Arjun Mehta arrives at a jewelry store in Mumbai where diamonds have been stolen.

The store CCTV captured 100 frames of data, each containing sensor readings.

Task:

• Create a 1D NumPy array of 100 integers (0–9) representing sensor triggers.

• Find out how many times the sensor detected activity (value > 5).


In [ ]:
import numpy as np

# Step 1: Create a 1D NumPy array of 100 integers (sensor readings)
# Random values between 0–9 simulate sensor triggers
sensor_data = np.random.randint(0, 10, size=100)

print("Sensor Data (first 20 values for preview):")
print(sensor_data[:20])   # show only first 20 for quick preview
print("------------------------------------------------------------")

# Step 2: Apply condition to detect activity (value > 5)
activity_mask = sensor_data > 5   # Boolean array (True where condition is met)

# Step 3: Count number of times activity detected
activity_count = np.sum(activity_mask)

# Step 4: Print result
print("\nTotal Activity Detected (value > 5):", activity_count)


Sensor Data (first 20 values for preview):
[7 8 7 1 9 0 9 1 1 2 9 6 1 0 5 8 2 5 2 0]
------------------------------------------------------------

Total Activity Detected (value > 5): 36


Scene 2: Suspect List

Inspector Rani Sharma provides a list of 20 suspects with their ages.

Ages are randomly assigned.

Task:

• Create a 1D array of 20 ages.

• Use fancy indexing to extract the ages of suspects with even indices.

• Find the youngest and oldest suspects.


In [ ]:
import numpy as np

# Step 1: Create a 1D array of 20 ages(random integers between 18–60 for realism)
ages = np.random.randint(18, 61, size=20)

print("All Suspects' Ages:")
print(ages)
print("----------------------------------------------------------------")

# Step 2: Fancy indexing → extract ages at even indices
even_indices = np.arange(0, len(ages), 2)   # generates [0,2,4,...,18]
even_index_ages = ages[even_indices]

print("\nAges of suspects at even indices:")
print(even_index_ages)

# Step 3: Find youngest and oldest suspects
youngest = np.min(ages)
oldest   = np.max(ages)

print("\nYoungest suspect age:", youngest)
print("Oldest suspect age:", oldest)

All Suspects' Ages:
[45 22 22 38 29 21 59 37 55 42 31 28 49 28 35 44 35 40 28 38]
----------------------------------------------------------------

Ages of suspects at even indices:
[45 22 29 59 55 31 49 35 35 28]

Youngest suspect age: 21
Oldest suspect age: 59


Scene 3: Witness Statement

A witness says: “I saw 5 people entering the store in pairs.”

CCTV logs show movements stored as a 10x2 matrix (10 rows, 2 values each: entry time and exit time).

Task:

• Create a 2D NumPy array of shape (10, 2) representing entry and exit times.

• Find the average entry time.

• Extract all rows where exit time < entry time + 5 minutes (suspicious quick visits).


In [ ]:
import numpy as np

# Step 1: Create a 2D array (10x2) for entry & exit times
# Let's assume entry times are between 0–50 mins,
# exit times between entry and entry+15 mins
np.random.seed(42)  # reproducibility
entry_times = np.random.randint(0, 50, size=10)
exit_times = entry_times + np.random.randint(1, 16, size=10)  # exit is always later

cctv_logs = np.column_stack((entry_times, exit_times))  # shape (10,2)

print("CCTV Logs (Entry, Exit):\n", cctv_logs)
print("----------------------------------------------------------------------")

# Step 2: Find average entry time
avg_entry = np.mean(cctv_logs[:, 0])  # take column 0
print("\nAverage entry time:", avg_entry)

# Step 3: Extract suspicious visits (exit < entry+5)
suspicious_visits = cctv_logs[cctv_logs[:, 1] < cctv_logs[:, 0] + 5]

print("\nSuspicious quick visits (<5 mins stay):\n", suspicious_visits)

CCTV Logs (Entry, Exit):
 [[38 49]
 [28 36]
 [14 19]
 [42 46]
 [ 7 15]
 [20 28]
 [38 41]
 [18 24]
 [22 27]
 [10 12]]
----------------------------------------------------------------------

Average entry time: 23.7

Suspicious quick visits (<5 mins stay):
 [[42 46]
 [38 41]
 [10 12]]


Scene 4: Car Parking Data

Outside the store, parking lot cameras recorded cars over 7 days and 5timeslots per day.

Task:

• Create a 2D array of shape (7, 5) representing number of cars.

• Find the day with maximum car traffic.

• Extract car counts for days [2, 4, 6] and time slots [1, 3] using fancy indexing.


In [ ]:
import numpy as np

# Step 1: Create a 2D array (7 days × 5 time slots)
# Each element = number of cars (random between 0–50)
np.random.seed(42)  # reproducibility
cars = np.random.randint(0, 51, size=(7, 5))

print("Parking Lot Data (7 days × 5 time slots):\n", cars)
print("------------------------------------------------------------")

# Step 2: Find the day with maximum car traffic
# Sum cars per day (row-wise), then find the day index with max total
daily_totals = cars.sum(axis=1)  # sum along columns
max_day = np.argmax(daily_totals)  # day index with max traffic

print("\nDaily totals:", daily_totals)
print("Day with maximum traffic (0-indexed):", max_day)

# Step 3: Extract car counts for days [2, 4, 6] and time slots [1, 3]
selected_counts = cars[[2, 4, 6]][:, [1, 3]]  # fancy row + fancy col indexing

print("\nCar counts for days [2, 4, 6] and slots [1, 3]:\n", selected_counts)

Parking Lot Data (7 days × 5 time slots):
 [[38 28 14 42  7]
 [20 38 18 22 10]
 [10 23 35 39 23]
 [ 2 21  1 23 43]
 [29 37  1 20 32]
 [11 21 43 24 48]
 [26 41 27 15 14]]
------------------------------------------------------------

Daily totals: [129 108 130  90 119 147 123]
Day with maximum traffic (0-indexed): 5

Car counts for days [2, 4, 6] and slots [1, 3]:
 [[23 39]
 [37 20]
 [41 15]]


Scene 5: Suspect Movements

Detective Arjun obtains GPS coordinates of 3 suspects over 4 days, with 2 readings/day.

Task:

• Create a 3D array of shape (3, 4, 2) → (suspects, days, coordinates).

• Transpose it to (4, 3, 2) to compare suspects day-wise.

• Extract locations of suspect 2 on days [1, 3].


In [ ]:
import numpy as np

# Step 1: Create a 3D array → (3 suspects, 4 days, 2 coordinates)
# Each coordinate = GPS (x, y), here simulated as random integers 0–100
np.random.seed(42)  # reproducibility
gps_data = np.random.randint(0, 101, size=(3, 4, 2))

print("Original GPS Data (suspect, day, coord):\n", gps_data)
print("Shape:", gps_data.shape)  # (3, 4, 2)
print("-------------------------------------------------------------------")

# Step 2: Transpose to (4, 3, 2) → (days, suspects, coordinates)
gps_daywise = np.transpose(gps_data, (1, 0, 2))

print("\nTransposed GPS Data (day, suspect, coord):\n", gps_daywise)
print("Shape:", gps_daywise.shape)  # (4, 3, 2)
print("-----------------------------------------------------------------")

# Step 3: Extract locations of suspect 2 (index 1) on days [1, 3]
# In original (suspect=1, days [1,3], coords [:])
suspect2_locations = gps_data[1, [1, 3], :]

print("\nLocations of Suspect 2 on Days [1, 3]:\n", suspect2_locations)

Original GPS Data (suspect, day, coord):
 [[[51 92]
  [14 71]
  [60 20]
  [82 86]]

 [[74 74]
  [87 99]
  [23  2]
  [21 52]]

 [[ 1 87]
  [29 37]
  [ 1 63]
  [59 20]]]
Shape: (3, 4, 2)
-------------------------------------------------------------------

Transposed GPS Data (day, suspect, coord):
 [[[51 92]
  [74 74]
  [ 1 87]]

 [[14 71]
  [87 99]
  [29 37]]

 [[60 20]
  [23  2]
  [ 1 63]]

 [[82 86]
  [21 52]
  [59 20]]]
Shape: (4, 3, 2)
-----------------------------------------------------------------

Locations of Suspect 2 on Days [1, 3]:
 [[87 99]
 [21 52]]


Scene 6: Hidden Transactions

Rani uncovers financial records of 5 suspects, each with 6 months of transactions.

Task:

• Create a 2D array of shape (5, 6).

• Find suspects whose average monthly spending > 50,000.

• Extract transactions of suspects [1, 3] in months [2, 4].


In [ ]:
import numpy as np

# Step 1: Create a 2D array → (5 suspects, 6 months)
# Random monthly transactions between 10,000 and 100,000
np.random.seed(42)  # reproducibility
transactions = np.random.randint(10000, 100001, size=(5, 6))

print("Transaction Data (suspect, month):\n", transactions)
print("Shape:", transactions.shape)  # (5, 6)
print("--------------------------------------------------------")

# Step 2: Find suspects whose average monthly spending > 50,000
avg_spending = transactions.mean(axis=1)  # mean across months for each suspect
high_spenders = np.where(avg_spending > 50000)[0]  # indices of suspects

print("\nAverage Monthly Spending of Each Suspect:\n", avg_spending)
print("Suspects with avg > 50,000:", high_spenders)
print("-------------------------------------------------------------")

# Step 3: Extract transactions of suspects [1, 3] in months [2, 4]
selected_transactions = transactions[[1, 3], :][:, [2, 4]]

print("\nTransactions of Suspects [1, 3] in Months [2, 4]:\n", selected_transactions)


Transaction Data (suspect, month):
 [[25795 10860 86820 64886 16265 92386]
 [47194 97498 54131 70263 26023 51090]
 [77221 74820 10769 69735 72955 74925]
 [77969 15311 93104 63707 95305 38693]
 [81932 35658 94478 28431 12747 69150]]
Shape: (5, 6)
--------------------------------------------------------

Average Monthly Spending of Each Suspect:
 [49502.         57699.83333333 63404.16666667 64014.83333333
 53732.66666667]
Suspects with avg > 50,000: [1 2 3 4]
-------------------------------------------------------------

Transactions of Suspects [1, 3] in Months [2, 4]:
 [[54131 26023]
 [93104 95305]]


Scene 7: Fingerprint Evidence

At the scene, police collected 3 fingerprint scans, each stored as a 4x4 pixel grayscale image.

Task:

• Create a 3D array of shape (3, 4, 4).

• Extract the center 2x2 region of each image.

• Replace all pixel values < 100 with 0 (noise removal).


In [ ]:
import numpy as np

# Step 1: Create a 3D array (3 fingerprints, 4x4 pixels each)
# Pixel values between 0–255 (grayscale)
np.random.seed(42)  # reproducibility
fingerprints = np.random.randint(0, 256, size=(3, 4, 4))

print("Original Fingerprint Scans:\n", fingerprints)
print("--------------------------------------------------------")


# Step 2: Extract the center 2x2 region of each image
# For 4x4 → center is rows [1,2], cols [1,2]
center_regions = fingerprints[:, 1:3, 1:3]

print("\nCenter 2x2 region from each fingerprint:\n", center_regions)
print("--------------------------------------------------------------")


# Step 3: Noise removal → replace values < 100 with 0
# Use boolean masking for efficiency
cleaned_fingerprints = np.where(fingerprints < 100, 0, fingerprints)

print("\nCleaned Fingerprint Scans (noise removed):\n", cleaned_fingerprints)


Original Fingerprint Scans:
 [[[102 179  92  14]
  [106  71 188  20]
  [102 121 210 214]
  [ 74 202  87 116]]

 [[ 99 103 151 130]
  [149  52   1  87]
  [235 157  37 129]
  [191 187  20 160]]

 [[203  57  21 252]
  [235  88  48 218]
  [ 58 254 169 255]
  [219 187 207  14]]]
--------------------------------------------------------

Center 2x2 region from each fingerprint:
 [[[ 71 188]
  [121 210]]

 [[ 52   1]
  [157  37]]

 [[ 88  48]
  [254 169]]]
--------------------------------------------------------------

Cleaned Fingerprint Scans (noise removed):
 [[[102 179   0   0]
  [106   0 188   0]
  [102 121 210 214]
  [  0 202   0 116]]

 [[  0 103 151 130]
  [149   0   0   0]
  [235 157   0 129]
  [191 187   0 160]]

 [[203   0   0 252]
  [235   0   0 218]
  [  0 254 169 255]
  [219 187 207   0]]]


Scene 8: Decoding the Cipher

The thieves left a coded message as numbers [65, 66, 67, 68, 69].

It maps to ASCII letters.

Task:

• Create a 1D array of ASCII values.

• Convert them into characters using vectorized operations (chr).

• Reveal the secret word.


In [ ]:
import numpy as np

# Step 1: Create a 1D array of ASCII values
ascii_values = np.array([65, 66, 67, 68, 69])

print("ASCII Values:", ascii_values)
print("----------------------------------------")

# Step 2: Convert ASCII values → characters
# Use vectorized operation: np.vectorize(chr)
chars = np.vectorize(chr)(ascii_values)

print("Characters:", chars)
print("-----------------------------------------------")

# Step 3: Join characters into a secret word
secret_word = ''.join(chars)

print("🔑 Secret Word Revealed:", secret_word)

ASCII Values: [65 66 67 68 69]
----------------------------------------
Characters: ['A' 'B' 'C' 'D' 'E']
-----------------------------------------------
🔑 Secret Word Revealed: ABCDE


Scene 9: Narrowing the Suspects

Based on data, only 4 suspects remain.

Their data includes height, weight, and age, stored in a 4x3 matrix.

Task:

• Create the array and label columns as [Height, Weight, Age].

• Extract suspects with weight > 70 and age < 30.


In [ ]:
import numpy as np

# Step 1: Create suspects data (Height in cm, Weight in kg, Age in years)
# Shape: (4 suspects, 3 features)
suspects = np.array([
    [175, 72, 25],   # Suspect 1
    [168, 65, 32],   # Suspect 2
    [182, 80, 28],   # Suspect 3
    [160, 55, 22]    # Suspect 4
])

# Labeling columns (for clarity)
columns = ["Height", "Weight", "Age"]

print("Suspects Data:\n", suspects)
print("\nColumns:", columns)
print("-------------------------------------")

# Step 2: Apply conditions
# weight > 70 AND age < 30
mask = (suspects[:, 1] > 70) & (suspects[:, 2] < 30)

# Step 3: Extract matching suspects
narrowed_suspects = suspects[mask]

print("\nFiltered Suspects (Weight > 70 & Age < 30):\n", narrowed_suspects)


Suspects Data:
 [[175  72  25]
 [168  65  32]
 [182  80  28]
 [160  55  22]]

Columns: ['Height', 'Weight', 'Age']
-------------------------------------

Filtered Suspects (Weight > 70 & Age < 30):
 [[175  72  25]
 [182  80  28]]


Scene 10: The Final Chase

CCTV confirms that 2 cars were used in the escape, tracked every 3 hours for 2 days.

Task:

• Create a 3D array of shape (2, 2, 8) → (cars, days, 8 time slots).

• Transpose it to (2, 8, 2) → (cars, time slots, days).

• Find at which time slot both cars were parked at the same location.

In [ ]:
import numpy as np

# Step 1: Create random car movement data
# Shape: (2 cars, 2 days, 8 time slots)
# Values represent "location IDs"
cars = np.random.randint(1, 6, size=(2, 2, 8))

print("Original Shape (Cars, Days, Time Slots):\n", cars)
print("-----------------------------------------------------")

# Step 2: Transpose -> (cars, time slots, days)
cars_transposed = cars.transpose(0, 2, 1)

print("\nTransposed Shape (Cars, Time Slots, Days):\n", cars_transposed)
print("------------------------------------------------------------------")

# Step 3: Find time slots where both cars have the same location (for ANY day)
# Compare locations across cars → axis 0
same_location_mask = cars_transposed[0] == cars_transposed[1]

# Step 4: Identify the time slots with matches
time_slots_same = np.where(same_location_mask)

print("\nSame Location Mask (True = both cars same location):\n", same_location_mask)
print("\nTime Slots where both cars same location (time slot index, day index):\n", list(zip(time_slots_same[0], time_slots_same[1])))

Original Shape (Cars, Days, Time Slots):
 [[[3 4 4 1 3 5 3 5]
  [1 2 4 1 4 2 2 1]]

 [[2 5 2 4 4 4 4 5]
  [3 1 4 2 4 2 2 4]]]
-----------------------------------------------------

Transposed Shape (Cars, Time Slots, Days):
 [[[3 1]
  [4 2]
  [4 4]
  [1 1]
  [3 4]
  [5 2]
  [3 2]
  [5 1]]

 [[2 3]
  [5 1]
  [2 4]
  [4 2]
  [4 4]
  [4 2]
  [4 2]
  [5 4]]]
------------------------------------------------------------------

Same Location Mask (True = both cars same location):
 [[False False]
 [False False]
 [False  True]
 [False False]
 [False  True]
 [False  True]
 [False  True]
 [ True False]]

Time Slots where both cars same location (time slot index, day index):
 [(np.int64(2), np.int64(1)), (np.int64(4), np.int64(1)), (np.int64(5), np.int64(1)), (np.int64(6), np.int64(1)), (np.int64(7), np.int64(0))]


The Verdict

After all the analysis, Detective Arjun Mehta and Inspector Rani Sharma
discover the mastermind:

• The suspect whose sensor activity matched,

• Car movement aligned, and

• Financial transactions spiked abnormally.

Final Task:

• Combine your extracted suspects’ data across all arrays and print the prime suspect ID.

In [ ]:
import numpy as np

# Step 1: Simulated suspects IDs
suspects = np.arange(1, 11)  # 10 suspects labeled 1–10

# Step 2: Evidence from different analyses
# Example: suspects flagged by different scenes
sensor_suspects = np.array([2, 4, 7, 9])      # from Scene 1
car_suspects = np.array([3, 7, 8])            # from Scene 10
finance_suspects = np.array([5, 7, 9])        # from Scene 6

print("Suspects flagged by sensors:", sensor_suspects)
print("Suspects flagged by car movements:", car_suspects)
print("Suspects flagged by finances:", finance_suspects)

# Step 3: Find common suspect(s) using intersections
prime_suspect = np.intersect1d(sensor_suspects, car_suspects)
prime_suspect = np.intersect1d(prime_suspect, finance_suspects)

# Step 4: Print the verdict
if prime_suspect.size > 0:
    print("\n Prime Suspect ID(s):", prime_suspect)
else:
    print("\nNo single suspect matches all conditions!")


Suspects flagged by sensors: [2 4 7 9]
Suspects flagged by car movements: [3 7 8]
Suspects flagged by finances: [5 7 9]

🔎 Prime Suspect ID(s): [7]


Detective Story: The Mystery of the Stolen Diamonds

Author: Detective Training Exercise

Goal: Practice all major NumPy operations through a
fun mystery case.

In [ ]:
import numpy as np

print("️ Scene 1: The Crime Scene")
print("Detective Arjun Mehta arrives at a jewelry store in Mumbai. Diamonds have been stolen!")
print("The CCTV captured 100 sensor readings (values 0–9).")

# Create 1D array of sensor data
sensor_data = np.random.randint(0, 10, size=100)

# TODO: Find how many times the sensor detected activity (>5)
high_activity_count = np.sum(sensor_data > 5)
print("\nScene 1 Result → High activity count:", high_activity_count)

# -------------------------------------------------

print("\n Scene 2: Suspect List")
print("Inspector Rani Sharma provides a list of 20 suspects with their ages.")
ages = np.random.randint(18, 60, size=20)

# TODO: Extract ages of suspects with even indices
even_index_ages = ages[::2]

# TODO: Find youngest and oldest suspects
youngest = np.min(ages)
oldest = np.max(ages)

print("\nScene 2 Result → Youngest:", youngest, "Oldest:", oldest)

# -------------------------------------------------

print("\n Scene 3: Witness Statement")
print("Witness says: 'I saw 5 people entering the store in pairs.'")
print("CCTV logs are stored as a 10x2 matrix (entry, exit times).")
cctv_logs = np.random.randint(0, 24, size=(10, 2))

# TODO: Average entry time
avg_entry = np.mean(cctv_logs[:, 0])

# TODO: Extract rows where exit < entry+5
quick_visits = cctv_logs[cctv_logs[:, 1] < cctv_logs[:, 0] + 5]

print("\nScene 3 Result → Suspicious visits:\n", quick_visits)

# -------------------------------------------------

print("\n Scene 4: Car Parking Data")
print("Parking lot cameras recorded cars for 7 days, 5 time slots each.")
cars = np.random.randint(0, 20, size=(7, 5))

# TODO: Find day with maximum car traffic
max_day = np.argmax(np.sum(cars, axis=1))

# TODO: Extract traffic for days [2,4,6] and time slots [1,3]
subset_traffic = cars[[2, 4, 6]][:, [1, 3]]

print("\nScene 4 Result → Max traffic day:", max_day)
print("Subset traffic:\n", subset_traffic)

# -------------------------------------------------

print("\n Scene 5: Suspect Movements")
print("GPS coordinates of 3 suspects, 4 days, 2 coords/day.")
gps = np.random.randint(0, 100, size=(3, 4, 2))

# TODO: Transpose to (4,3,2)
gps_transposed = gps.transpose(1, 0, 2)

# TODO: Extract suspect 2 on days [1,3]
suspect2_movements = gps[1, [1, 3]]

print("\nScene 5 Result → Movements of suspect 2:\n", suspect2_movements)

# -------------------------------------------------

print("\n️ Scene 6: Hidden Transactions")
print("Financial records of 5 suspects, 6 months.")
transactions = np.random.randint(20000, 100000, size=(5, 6))

# TODO: Find suspects with avg spending > 50,000
big_spenders = np.where(np.mean(transactions, axis=1) > 50000)[0]

# TODO: Extract suspects [1,3] months [2,4]
special_tx = transactions[[1, 3]][:, [2, 4]]

print("\nScene 6 Result → Big spenders:", big_spenders)
print("Special extracted transactions:\n", special_tx)

# -------------------------------------------------

print("\n Scene 7: Fingerprint Evidence")
print("3 fingerprint scans as 4x4 images.")
fingerprints = np.random.randint(0, 255, size=(3, 4, 4))

# TODO: Extract center 2x2 region of each image
centers = fingerprints[:, 1:3, 1:3]

# TODO: Replace pixels < 100 with 0
fingerprints_clean = fingerprints.copy()
fingerprints_clean[fingerprints_clean < 100] = 0

print("\nScene 7 Result → Cleaned fingerprints:\n", fingerprints_clean)

# -------------------------------------------------

print("\n Scene 8: Decoding the Cipher")
print("A coded message: [65, 66, 67, 68, 69]")
cipher = np.array([65, 66, 67, 68, 69])

# TODO: Convert to characters
message = ''.join(map(chr, cipher))
print("\nScene 8 Result → Secret message:", message)

# -------------------------------------------------

print("\n Scene 9: Narrowing the Suspects")
print("Remaining 4 suspects: Height, Weight, Age")
suspects_data = np.random.randint(20, 100, size=(4, 3))

# TODO: Extract suspects with weight > 70 and age < 30
filtered_suspects = suspects_data[(suspects_data[:, 1] > 70) & (suspects_data[:, 2] < 30)]
print("\nScene 9 Result → Filtered suspects:\n", filtered_suspects)

# -------------------------------------------------

print("\n️ Scene 10: The Final Chase")
print("2 cars tracked every 3 hours for 2 days → shape (2,2,8)")
cars_tracking = np.random.randint(0, 50, size=(2, 2, 8))

# TODO: Transpose to (2,8,2)
cars_transposed = cars_tracking.transpose(0, 2, 1)

# TODO: Find times both cars share same location
same_location_times = np.where(cars_transposed[0] == cars_transposed[1])
print("\nScene 10 Result → Same location times:", same_location_times)

# -------------------------------------------------

print("\n️ Final Verdict")
print("Combine results to reveal the PRIME SUSPECT!")

# TODO: Combine logic → pick suspect ID based on patterns
prime_suspect = big_spenders[0] if len(big_spenders) > 0 else "Unknown"
print("\n The Prime Suspect is:", prime_suspect)


️ Scene 1: The Crime Scene
Detective Arjun Mehta arrives at a jewelry store in Mumbai. Diamonds have been stolen!
The CCTV captured 100 sensor readings (values 0–9).

Scene 1 Result → High activity count: 52

 Scene 2: Suspect List
Inspector Rani Sharma provides a list of 20 suspects with their ages.

Scene 2 Result → Youngest: 18 Oldest: 58

 Scene 3: Witness Statement
Witness says: 'I saw 5 people entering the store in pairs.'
CCTV logs are stored as a 10x2 matrix (entry, exit times).

Scene 3 Result → Suspicious visits:
 [[20 11]
 [16  5]
 [23  4]
 [19  1]
 [15  0]]

 Scene 4: Car Parking Data
Parking lot cameras recorded cars for 7 days, 5 time slots each.

Scene 4 Result → Max traffic day: 1
Subset traffic:
 [[19  0]
 [ 9  6]
 [11  4]]

 Scene 5: Suspect Movements
GPS coordinates of 3 suspects, 4 days, 2 coords/day.

Scene 5 Result → Movements of suspect 2:
 [[74 71]
 [83 98]]

️ Scene 6: Hidden Transactions
Financial records of 5 suspects, 6 months.

Scene 6 Result → Big spenders